[theme]
primarycolor = "#E85D04"
backgroundcolor = "#c4b6c4ff"
secondaryBackgroundColor = "#FFF4EC"
textColor = "#2B2118"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
runOnSave = true

